import styles from './globals.css'
import Link from 'next/link'



export const metadata = {
  title: 'Tienda Falsa',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={styles.body}>
        <header className={styles.header}>
          <h1>Tienda de productos</h1>
        </header>
        <nav className={styles.nav}>
          <Link href={'/'}>Carts</Link>
          <Link href={'/productos'}>Productos</Link>
        </nav>
        <main className={styles.main}>
          <h2 >Carrito de compras</h2>
          {children}
        </main>

        <footer className={styles.footer}>
          <h3>Miguel_loopez @ Siuuu</h3>
        </footer>
      </body>
    </html>
  )
}
